---
title: "Replication of Study 1 by Korman and Khemlani (2020, Cognition)"
author: "Joanna Korman (jkorman@mitre.com) and Sangeet Khemlani"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: false
---

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

##Introduction

Psychological essentialism holds that some concepts represent their categories as having an inner quality, an essence—the underlying property that causes observable features—that isn’t directly observable (e.g., Medin & Ortony 1989). Essentialized categories are represented as having a true nature which is assumed to be shared among category members and responsible for similarities among members of a category (Gelman and Ware, 2012).  

One central question raised by psychological essentialism is whether essences are represented in terms of placeholders or with specified contents. My view is that essences aren't always represented in terms of placeholders. Instead placeholders are typically elaborated. And when they are the content of an essentialized category is given by a kind of purpose or telos. 

A range of evidence suggests that generics are a central vehicle by which essentialist assumptions about some categories are transmitted (e.g., Rhodes, Leslie, Tworek, 2012; Gelman, Ware & Kleinberg, 2010).  But so far this work has focused on a traits, attitudes, or superficial properties, all of which are plausibly not viewed as tele. For instance, Gelman et al (2010) and Rhodes et al (2012) focus on generics such as “Zarpies have stripes”, “Zarpies are orange”, “Zarpies are scared of ladybugs” and “Zarpies hate ice cream”. Exposure to these over their non-generic counterparts (e.g., This zarpie hates ice cream) leads both children and adults to tend to essentialize the category (i.e., zarpies). My question is whether generics amplify essentialist inferences when candidate features are thought to be associated with a thing's purpose, as opposed to merely reflecting e.g., superficial properties and traits. 

Some recent work that serves as part of the backdrop for my own research on this issue comes from Korman and Khemlani (2020) who investigate what they call "teleological generics" which are generic generalizations that concern purposes or functions. They propose that people are more inclined to accept some teleological generics such as "cars are for driving" over others, such as "cars are for parking" when the feature or property bears a principled connection to the category.  One linguistic test of whether a property bears a principled connection to a category concerns whether one finds self-referential generalizations, e.g., Xs, by virtue of being Xs, are Y, acceptable.  So they predict that acceptance of teleological generics will be correlated with acceptance of self-referential generalizations.  In other words, people should be more inclined to accept "cars are for driving" than "cars are for parking" to the extent that they accept "cars, by virtue of being cars, are for driving" over "cars, by virtue of being cars, are for parking".  This is what is explored in their Experimement 1, which will be the focus of my replication.

In Experiemnt 1 of Korman and Khemlani (2020), they presented half of their participants with a number of differnet teleological generic statements--i.e., assertions of the form NPplural+VPpurposive, e.g., “cars” + “are for driving”--that varied in whether the noun concerned arifacts (e.g., chairs) or biological parts (e.g., eyes) and whether the verbs, experiemnetal and control, yeilded either acceptable generalizations (e.g., chairs are for sitting, eyes or for seeing) or false generalizations (e.g., chairs are for dusting, eyes are for blinking). The other half of participants recived those same statements in the form of self-referential generalizations (e.g., chairs, in virtue of being chairs, are for sitting, chairs, in virtue of being chairs, are for dusting). Participnats indicated whether they thought the statement was true or false on a 7pt Likert scale raning from -3 (definitely false) to 3 (definitely true). Their study thus involved a mixed design with Statement Type(Teleological Generic, Self-Referential Generalization) as a between-subjects factor and Verb(Experimental, Control) as a within-subjects factor. I don't anticipate any major challenges in implementing this replication.

The link to the repository is [here](https://github.com/psych251/korman2020) and the link to the paper is [here]()



##Methods

###Power Analysis

Original effect size, power analysis for samples to achieve 80%, 90%, 95% power to detect that effect size.  Considerations of feasibility for selecting planned sample size.

###Planned Sample

Planned sample size and/or termination rule, sampling frame, known demographics if any, preselection rules if any.

###Materials

All materials - can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

###Procedure	

Can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

###Analysis Plan

Can also quote directly, though it is less often spelled out effectively for an analysis strategy section.  The key is to report an analysis strategy that is as close to the original - data cleaning rules, data exclusion rules, covariates, etc. - as possible.  

**Clarify key analysis of interest here**  You can also pre-specify additional analyses you plan to do.

###Differences from Original Study

Explicitly describe known differences in sample, setting, procedure, and analysis plan from original study.  The goal, of course, is to minimize those differences, but differences will inevitably occur.  Also, note whether such differences are anticipated to make a difference based on claims in the original article or subsequent published research on the conditions for obtaining the effect.

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


##Results


### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
###Data Preparation

####Load Relevant Libraries and Functions

####Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

###Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
